sources:
  - name: src
    database: sourcedb
    schema: mkmall

    tables:
      - name: customers
      - name: nations
        columns:
          -  name: n_nationkey
             data_tests:
              -  unique
              -  not_null
        
      - name: regions
        description: Raw data for regions
      - name: lineitems
        
      - name: orders
        config:
          freshness:
            warn_after: 
              count: 154
              period: day
            error_after: 
              count: 300
              period: day
          loaded_at_field: o_orderdate::timestamp_ntz
      - name: parts
      - name: partsupps
      - name: suppliers
      
  - name: ext_murali
    database: ANALYTICS
    schema: dbt_murali
    tables:
      - name: supplier_names
